version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: weekly
    time: '14:00'
    timezone: America/Detroit
  open-pull-requests-limit: 10
  reviewers:
  - mcansh
  labels:
  - dependencies
