service: blog

provider:
  name: aws
  runtime: nodejs8.10
  memorySize: 512

stage: dev
region: eu-west-1

plugins:
  - serverless-nextjs-plugin
  - serverless-offline

custom:
  serverless-nextjs:
    assetsBucketName: 'logan-mcansh-blog'


package:
  # exclude everything
  # page handlers are automatically included by the plugin
  exclude:
    - ./**
