// flow-typed signature: 0580f7cf90c9836468cf7cc0b5edabc1
// flow-typed version: <<STUB>>/@sentry/browser_v4.2.3/flow_v0.85.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@sentry/browser'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@sentry/browser' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@sentry/browser/build/bundle' {
  declare module.exports: any;
}

declare module '@sentry/browser/build/bundle.min' {
  declare module.exports: any;
}

declare module '@sentry/browser/dist/index' {
  declare module.exports: any;
}

// Filename aliases
declare module '@sentry/browser/build/bundle.js' {
  declare module.exports: $Exports<'@sentry/browser/build/bundle'>;
}
declare module '@sentry/browser/build/bundle.min.js' {
  declare module.exports: $Exports<'@sentry/browser/build/bundle.min'>;
}
declare module '@sentry/browser/dist/index.js' {
  declare module.exports: $Exports<'@sentry/browser/dist/index'>;
}
