// flow-typed signature: 64e9acf1616d502989704bc2e6ccd4bc
// flow-typed version: <<STUB>>/apollo-boost_v0.1.19/flow_v0.85.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'apollo-boost'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'apollo-boost' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'apollo-boost/lib/bundle.umd' {
  declare module.exports: any;
}

declare module 'apollo-boost/lib/index' {
  declare module.exports: any;
}

declare module 'apollo-boost/lib/index.umd' {
  declare module.exports: any;
}

declare module 'apollo-boost/rollup-bundle.config' {
  declare module.exports: any;
}

// Filename aliases
declare module 'apollo-boost/lib/bundle.umd.js' {
  declare module.exports: $Exports<'apollo-boost/lib/bundle.umd'>;
}
declare module 'apollo-boost/lib/index.js' {
  declare module.exports: $Exports<'apollo-boost/lib/index'>;
}
declare module 'apollo-boost/lib/index.umd.js' {
  declare module.exports: $Exports<'apollo-boost/lib/index.umd'>;
}
declare module 'apollo-boost/rollup-bundle.config.js' {
  declare module.exports: $Exports<'apollo-boost/rollup-bundle.config'>;
}
