// flow-typed signature: 9cda761e993dd5856edf4e3ada12ff58
// flow-typed version: <<STUB>>/imagemin_v6.0.0/flow_v0.83.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'imagemin'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'imagemin' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'imagemin/index' {
  declare module.exports: $Exports<'imagemin'>;
}
declare module 'imagemin/index.js' {
  declare module.exports: $Exports<'imagemin'>;
}
