// flow-typed signature: 9c6dbf9806da1e7858011011fc72d848
// flow-typed version: <<STUB>>/imagemin-webp_v4.1.0/flow_v0.85.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'imagemin-webp'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'imagemin-webp' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'imagemin-webp/index' {
  declare module.exports: $Exports<'imagemin-webp'>;
}
declare module 'imagemin-webp/index.js' {
  declare module.exports: $Exports<'imagemin-webp'>;
}
