// flow-typed signature: 8c7fe5e2691f935cf69a1df005ee8eef
// flow-typed version: <<STUB>>/inquirer-path_v1.0.0-beta5/flow_v0.85.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'inquirer-path'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'inquirer-path' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'inquirer-path/lib/index' {
  declare module.exports: any;
}

declare module 'inquirer-path/lib/Path' {
  declare module.exports: any;
}

declare module 'inquirer-path/lib/PathAutocomplete' {
  declare module.exports: any;
}

declare module 'inquirer-path/lib/PathPrompt' {
  declare module.exports: any;
}

declare module 'inquirer-path/lib/PathPromptRenderer' {
  declare module.exports: any;
}

// Filename aliases
declare module 'inquirer-path/lib/index.js' {
  declare module.exports: $Exports<'inquirer-path/lib/index'>;
}
declare module 'inquirer-path/lib/Path.js' {
  declare module.exports: $Exports<'inquirer-path/lib/Path'>;
}
declare module 'inquirer-path/lib/PathAutocomplete.js' {
  declare module.exports: $Exports<'inquirer-path/lib/PathAutocomplete'>;
}
declare module 'inquirer-path/lib/PathPrompt.js' {
  declare module.exports: $Exports<'inquirer-path/lib/PathPrompt'>;
}
declare module 'inquirer-path/lib/PathPromptRenderer.js' {
  declare module.exports: $Exports<'inquirer-path/lib/PathPromptRenderer'>;
}
