// flow-typed signature: 74cdd6a4330f3d390e1208222e35f8e8
// flow-typed version: <<STUB>>/isomorphic-path_v0.0.5/flow_v0.85.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'isomorphic-path'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'isomorphic-path' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'isomorphic-path/dist/isomorphic-path.browser' {
  declare module.exports: any;
}

declare module 'isomorphic-path/dist/isomorphic-path' {
  declare module.exports: any;
}

declare module 'isomorphic-path/temp/test/browserRunner' {
  declare module.exports: any;
}

declare module 'isomorphic-path/temp/test/nodeRunner' {
  declare module.exports: any;
}

declare module 'isomorphic-path/webpack.config.browser' {
  declare module.exports: any;
}

declare module 'isomorphic-path/webpack.config.browser.test' {
  declare module.exports: any;
}

declare module 'isomorphic-path/webpack.config' {
  declare module.exports: any;
}

declare module 'isomorphic-path/webpack.config.test' {
  declare module.exports: any;
}

// Filename aliases
declare module 'isomorphic-path/dist/isomorphic-path.browser.js' {
  declare module.exports: $Exports<'isomorphic-path/dist/isomorphic-path.browser'>;
}
declare module 'isomorphic-path/dist/isomorphic-path.js' {
  declare module.exports: $Exports<'isomorphic-path/dist/isomorphic-path'>;
}
declare module 'isomorphic-path/temp/test/browserRunner.js' {
  declare module.exports: $Exports<'isomorphic-path/temp/test/browserRunner'>;
}
declare module 'isomorphic-path/temp/test/nodeRunner.js' {
  declare module.exports: $Exports<'isomorphic-path/temp/test/nodeRunner'>;
}
declare module 'isomorphic-path/webpack.config.browser.js' {
  declare module.exports: $Exports<'isomorphic-path/webpack.config.browser'>;
}
declare module 'isomorphic-path/webpack.config.browser.test.js' {
  declare module.exports: $Exports<'isomorphic-path/webpack.config.browser.test'>;
}
declare module 'isomorphic-path/webpack.config.js' {
  declare module.exports: $Exports<'isomorphic-path/webpack.config'>;
}
declare module 'isomorphic-path/webpack.config.test.js' {
  declare module.exports: $Exports<'isomorphic-path/webpack.config.test'>;
}
