// flow-typed signature: 0a6a1ec972d9d33cd4d3cea2af7788c1
// flow-typed version: <<STUB>>/kleur_v2.0.2/flow_v0.85.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'kleur'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'kleur' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'kleur/index' {
  declare module.exports: $Exports<'kleur'>;
}
declare module 'kleur/index.js' {
  declare module.exports: $Exports<'kleur'>;
}
