// flow-typed signature: 6d8c60cf2abea39c051d644740be6419
// flow-typed version: <<STUB>>/next-offline_v3.0.2/flow_v0.83.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'next-offline'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'next-offline' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'next-offline/export' {
  declare module.exports: any;
}

declare module 'next-offline/next-manifest' {
  declare module.exports: any;
}

declare module 'next-offline/plugin' {
  declare module.exports: any;
}

declare module 'next-offline/register-sw' {
  declare module.exports: any;
}

declare module 'next-offline/service-worker' {
  declare module.exports: any;
}

// Filename aliases
declare module 'next-offline/export.js' {
  declare module.exports: $Exports<'next-offline/export'>;
}
declare module 'next-offline/index' {
  declare module.exports: $Exports<'next-offline'>;
}
declare module 'next-offline/index.js' {
  declare module.exports: $Exports<'next-offline'>;
}
declare module 'next-offline/next-manifest.js' {
  declare module.exports: $Exports<'next-offline/next-manifest'>;
}
declare module 'next-offline/plugin.js' {
  declare module.exports: $Exports<'next-offline/plugin'>;
}
declare module 'next-offline/register-sw.js' {
  declare module.exports: $Exports<'next-offline/register-sw'>;
}
declare module 'next-offline/service-worker.js' {
  declare module.exports: $Exports<'next-offline/service-worker'>;
}
