// flow-typed signature: ca00dcd2f2e1d9af9cafbaac9285eec5
// flow-typed version: <<STUB>>/next-size_v1.0.1/flow_v0.85.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'next-size'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'next-size' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'next-size/example/pages/index' {
  declare module.exports: any;
}

declare module 'next-size/lib/asset-size-plugin' {
  declare module.exports: any;
}

// Filename aliases
declare module 'next-size/example/pages/index.js' {
  declare module.exports: $Exports<'next-size/example/pages/index'>;
}
declare module 'next-size/index' {
  declare module.exports: $Exports<'next-size'>;
}
declare module 'next-size/index.js' {
  declare module.exports: $Exports<'next-size'>;
}
declare module 'next-size/lib/asset-size-plugin.js' {
  declare module.exports: $Exports<'next-size/lib/asset-size-plugin'>;
}
