// flow-typed signature: 588df62101a8dd1cc9060d2f00d64ed3
// flow-typed version: <<STUB>>/next-with-apollo_v3.2.1/flow_v0.85.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'next-with-apollo'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'next-with-apollo' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'next-with-apollo/jest.config' {
  declare module.exports: any;
}

declare module 'next-with-apollo/lib/__tests__/smoke' {
  declare module.exports: any;
}

declare module 'next-with-apollo/lib/apollo' {
  declare module.exports: any;
}

declare module 'next-with-apollo/lib/apolloApp' {
  declare module.exports: any;
}

declare module 'next-with-apollo/lib/getDataFromTree' {
  declare module.exports: any;
}

declare module 'next-with-apollo/lib/index' {
  declare module.exports: any;
}

declare module 'next-with-apollo/lib/types' {
  declare module.exports: any;
}

declare module 'next-with-apollo/lib/withApollo' {
  declare module.exports: any;
}

// Filename aliases
declare module 'next-with-apollo/jest.config.js' {
  declare module.exports: $Exports<'next-with-apollo/jest.config'>;
}
declare module 'next-with-apollo/lib/__tests__/smoke.js' {
  declare module.exports: $Exports<'next-with-apollo/lib/__tests__/smoke'>;
}
declare module 'next-with-apollo/lib/apollo.js' {
  declare module.exports: $Exports<'next-with-apollo/lib/apollo'>;
}
declare module 'next-with-apollo/lib/apolloApp.js' {
  declare module.exports: $Exports<'next-with-apollo/lib/apolloApp'>;
}
declare module 'next-with-apollo/lib/getDataFromTree.js' {
  declare module.exports: $Exports<'next-with-apollo/lib/getDataFromTree'>;
}
declare module 'next-with-apollo/lib/index.js' {
  declare module.exports: $Exports<'next-with-apollo/lib/index'>;
}
declare module 'next-with-apollo/lib/types.js' {
  declare module.exports: $Exports<'next-with-apollo/lib/types'>;
}
declare module 'next-with-apollo/lib/withApollo.js' {
  declare module.exports: $Exports<'next-with-apollo/lib/withApollo'>;
}
