// flow-typed signature: fa357656d1422eb3d5db846c72e6cebf
// flow-typed version: <<STUB>>/polka_v0.5.1/flow_v0.83.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'polka'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'polka' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'polka/index' {
  declare module.exports: $Exports<'polka'>;
}
declare module 'polka/index.js' {
  declare module.exports: $Exports<'polka'>;
}
