// flow-typed signature: 5c0b6c8634337ce19b9fc6df7dcf02e2
// flow-typed version: <<STUB>>/prop-types-exact_v1.2.0/flow_v0.83.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'prop-types-exact'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'prop-types-exact' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'prop-types-exact/build/helpers/isPlainObject' {
  declare module.exports: any;
}

declare module 'prop-types-exact/build/index' {
  declare module.exports: any;
}

declare module 'prop-types-exact/build/sloppy' {
  declare module.exports: any;
}

declare module 'prop-types-exact/src/helpers/isPlainObject' {
  declare module.exports: any;
}

declare module 'prop-types-exact/src/index' {
  declare module.exports: any;
}

declare module 'prop-types-exact/src/sloppy' {
  declare module.exports: any;
}

declare module 'prop-types-exact/test/helpers/_failTestsOnErrors' {
  declare module.exports: any;
}

declare module 'prop-types-exact/test/helpers/callValidator' {
  declare module.exports: any;
}

declare module 'prop-types-exact/test/index' {
  declare module.exports: any;
}

declare module 'prop-types-exact/test/sloppy' {
  declare module.exports: any;
}

// Filename aliases
declare module 'prop-types-exact/build/helpers/isPlainObject.js' {
  declare module.exports: $Exports<'prop-types-exact/build/helpers/isPlainObject'>;
}
declare module 'prop-types-exact/build/index.js' {
  declare module.exports: $Exports<'prop-types-exact/build/index'>;
}
declare module 'prop-types-exact/build/sloppy.js' {
  declare module.exports: $Exports<'prop-types-exact/build/sloppy'>;
}
declare module 'prop-types-exact/src/helpers/isPlainObject.js' {
  declare module.exports: $Exports<'prop-types-exact/src/helpers/isPlainObject'>;
}
declare module 'prop-types-exact/src/index.js' {
  declare module.exports: $Exports<'prop-types-exact/src/index'>;
}
declare module 'prop-types-exact/src/sloppy.js' {
  declare module.exports: $Exports<'prop-types-exact/src/sloppy'>;
}
declare module 'prop-types-exact/test/helpers/_failTestsOnErrors.js' {
  declare module.exports: $Exports<'prop-types-exact/test/helpers/_failTestsOnErrors'>;
}
declare module 'prop-types-exact/test/helpers/callValidator.js' {
  declare module.exports: $Exports<'prop-types-exact/test/helpers/callValidator'>;
}
declare module 'prop-types-exact/test/index.jsx' {
  declare module.exports: $Exports<'prop-types-exact/test/index'>;
}
declare module 'prop-types-exact/test/sloppy.jsx' {
  declare module.exports: $Exports<'prop-types-exact/test/sloppy'>;
}
