// flow-typed signature: 5e0ee5f4b43369c2cc0310e5e88bfc50
// flow-typed version: <<STUB>>/react-adopt_v0.6.0/flow_v0.83.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-adopt'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-adopt' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-adopt/dist/index' {
  declare module.exports: any;
}

declare module 'react-adopt/dist/index.m' {
  declare module.exports: any;
}

declare module 'react-adopt/dist/index.umd' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-adopt/dist/index.js' {
  declare module.exports: $Exports<'react-adopt/dist/index'>;
}
declare module 'react-adopt/dist/index.m.js' {
  declare module.exports: $Exports<'react-adopt/dist/index.m'>;
}
declare module 'react-adopt/dist/index.umd.js' {
  declare module.exports: $Exports<'react-adopt/dist/index.umd'>;
}
