// flow-typed signature: 22d9929adea3f0fb89f9dd1f21503ba5
// flow-typed version: <<STUB>>/remark-emoji_v2.0.2/flow_v0.83.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'remark-emoji'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'remark-emoji' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'remark-emoji/index_test' {
  declare module.exports: any;
}

// Filename aliases
declare module 'remark-emoji/index_test.js' {
  declare module.exports: $Exports<'remark-emoji/index_test'>;
}
declare module 'remark-emoji/index' {
  declare module.exports: $Exports<'remark-emoji'>;
}
declare module 'remark-emoji/index.js' {
  declare module.exports: $Exports<'remark-emoji'>;
}
