// flow-typed signature: 50b8e13004e0e783d497408f16e7e13d
// flow-typed version: <<STUB>>/somebody_v2.0.0/flow_v0.83.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'somebody'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'somebody' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'somebody/index' {
  declare module.exports: $Exports<'somebody'>;
}
declare module 'somebody/index.js' {
  declare module.exports: $Exports<'somebody'>;
}
