// flow-typed signature: 7f442abdd0c2d33db8a98f5923281baf
// flow-typed version: <<STUB>>/tinydate_v1.0.0/flow_v0.83.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'tinydate'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'tinydate' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'tinydate/dist/tinydate.es' {
  declare module.exports: any;
}

declare module 'tinydate/dist/tinydate' {
  declare module.exports: any;
}

declare module 'tinydate/dist/tinydate.min' {
  declare module.exports: any;
}

// Filename aliases
declare module 'tinydate/dist/tinydate.es.js' {
  declare module.exports: $Exports<'tinydate/dist/tinydate.es'>;
}
declare module 'tinydate/dist/tinydate.js' {
  declare module.exports: $Exports<'tinydate/dist/tinydate'>;
}
declare module 'tinydate/dist/tinydate.min.js' {
  declare module.exports: $Exports<'tinydate/dist/tinydate.min'>;
}
