// flow-typed signature: 29253722dc02a430f6a0042f8d5734b3
// flow-typed version: <<STUB>>/tmp-cache_v1.0.0/flow_v0.85.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'tmp-cache'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'tmp-cache' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'tmp-cache/lib/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'tmp-cache/lib/index.js' {
  declare module.exports: $Exports<'tmp-cache/lib/index'>;
}
