// flow-typed signature: c74e538a2882b6bf7efaf2373b8ceaa7
// flow-typed version: <<STUB>>/@sindresorhus/slugify_v0.4.0/flow_v0.83.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@sindresorhus/slugify'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@sindresorhus/slugify' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module '@sindresorhus/slugify/index' {
  declare module.exports: $Exports<'@sindresorhus/slugify'>;
}
declare module '@sindresorhus/slugify/index.js' {
  declare module.exports: $Exports<'@sindresorhus/slugify'>;
}
