// flow-typed signature: 54afd1405387190a69a079216fdf5525
// flow-typed version: <<STUB>>/@zeit/git-hooks_v0.1.4/flow_v0.83.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@zeit/git-hooks'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@zeit/git-hooks' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@zeit/git-hooks/git-dir' {
  declare module.exports: any;
}

declare module '@zeit/git-hooks/install' {
  declare module.exports: any;
}

declare module '@zeit/git-hooks/null' {
  declare module.exports: any;
}

declare module '@zeit/git-hooks/uninstall' {
  declare module.exports: any;
}

// Filename aliases
declare module '@zeit/git-hooks/git-dir.js' {
  declare module.exports: $Exports<'@zeit/git-hooks/git-dir'>;
}
declare module '@zeit/git-hooks/install.js' {
  declare module.exports: $Exports<'@zeit/git-hooks/install'>;
}
declare module '@zeit/git-hooks/null.js' {
  declare module.exports: $Exports<'@zeit/git-hooks/null'>;
}
declare module '@zeit/git-hooks/uninstall.js' {
  declare module.exports: $Exports<'@zeit/git-hooks/uninstall'>;
}
