name: Lighthouse Check

on: [pull_request]

jobs:
  test_setup:
    name: Test setup
    runs-on: ubuntu-latest
    outputs:
      preview_url: ${{ steps.waitForVercelPreviewDeployment.outputs.url }}
    steps:
      - name: Wait for Vercel preview deployment to be ready
        uses: patrickedqvist/wait-for-vercel-preview@master
        id: waitForVercelPreviewDeployment
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          max_timeout: 60
  test_lighthouse:
    name: Lighthouse Check
    needs: test_setup
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Lighthouse Check
        uses: foo-software/lighthouse-check-action@master
        with:
          urls: |
            ${{ needs.test_setup.outputs.preview_url }}
