on: push
name: Send coverage to codecov
jobs:
  eslint:
    name: ESLint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: ESLint checks
        uses: gimenete/eslint-action@1.0

  codecov:
    name: Codecov
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Codecov
      uses: Atrox/codecov-action@v0.1.3
      env:
        CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
