// flow-typed signature: 5aff472d31d4f193ec1456157bd8aaf9
// flow-typed version: <<STUB>>/@polka/send-type_v0.5.0/flow_v0.83.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@polka/send-type'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@polka/send-type' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module '@polka/send-type/index' {
  declare module.exports: $Exports<'@polka/send-type'>;
}
declare module '@polka/send-type/index.js' {
  declare module.exports: $Exports<'@polka/send-type'>;
}
